public enum TIPO_APONTAMENTO
{
    INICIAL,
    KM_INICIAL,
    HORIMETRO_INICIAL,
    SAIDA_GARAGEM,
    INICIO_COLETA,
    FIM_COLETA,
    INICIO_REFEICAO,
    FIM_REFEICAO,

    BALANCA,
    INICIO_DESCARGA,
    FIM_DESCARGA,
    TICKET_BALANCA,
    PESO_LIQUIDO,
    HORIMETRO_FINAL,
    KM_FINAL

    
}